Resources:
    StudentTable:
        Type: AWS::DynamoDB::Table
        Properties:
            TableName: ${self:custom.DYNAMODB_STUDENT_TABLE}
            AttributeDefinitions:
                - AttributeName: ID
                  AttributeType: S
            KeySchema:
                - AttributeName: ID
                  KeyType: HASH
            BillingMode: PAY_PER_REQUEST